spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/employee_directory
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
  data:
    rest:
      # this define the base path before accessing to the rest repo
      base-path: nhanvien
#      default-page-size:
#      max-page-size: