spring:
  application:
    name: demo
  datasource:
    url: jdbc:mysql://localhost:3306/student_tracker
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update